name: Run JMeter Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Install JMeter
        run: |
         wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
         tar -xf apache-jmeter-5.6.3.tgz
         sudo mv apache-jmeter-5.6.3 /opt/
         echo 'export PATH=/opt/apache-jmeter-5.6.3/bin:$PATH' >> ~/.bashrc
         source ~/.bashrc

      - name: Run JMeter tests
        run: |
          ./apache-jmeter-5.4.1/bin/jmeter -n -t "testingHTTP(S) Test Script Recorder.jmx" -l report/results.jtl -e -o reports

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
         name: jmeter-results
         path: ./results/result.jtl
