name: Run JMeter Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Install JMeter
        run: |
         wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
         tar -xf apache-jmeter-5.6.3.tgz
         sudo mv apache-jmeter-5.6.3 /opt/
         echo 'export PATH=/opt/apache-jmeter-5.6.3/bin:$PATH' >> ~/.bashrc
         source ~/.bashrc

      - name: Download and Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/
          echo 'export PATH=/opt/apache-jmeter-5.6.3/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
      - name: Run JMeter Tests
        run: /opt/apache-jmeter-5.6.3/bin/jmeter -n -t "testingHTTP(S) Test Script Recorder.jmx"

      - name: Upload results to Report Portal
        run: |
          curl -X POST \
            -H "Authorization: Bearer report_7QbUgJvxQomWUspSTzLoBTVnncIDDr6ffzlO_7-_dhAQZbBWJsghBlhDOqHSIyLB" \
            -H "Content-Type: application/json" \
            --data-binary "@reports" \
            "http://nashtech-test-reportportal.eastasia.cloudapp.azure.com:8080/api/v1/import/launch" \
            -d '{"name": "RENU", "project": "automation"}'
