name: Run JMeter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'  # or 'zulu', 'temurin', etc.
        java-version: '11'     # or any other version required by your JMeter tests

    - name: Download and install JMeter
      run: |
        JMETER_VERSION="5.5"
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
        tar -xvzf apache-jmeter-$JMETER_VERSION.tgz
        echo "export PATH=$PATH:$GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/bin" >> $GITHUB_ENV

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run JMeter test for HTTP(S) Recorder
      shell: bash
      run: |
        export PATH=$PATH:$GITHUB_WORKSPACE/apache-jmeter-5.5/bin
        jmeter -n -t "testingHTTP(S) Test Script Recorder.jmx" -l reports/results_http_recorder.jtl -e -o reports/output_http_recorder

    - name: Upload JMeter results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: reports
