name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt' 
        java-version: '21' 

    - name: Download and install JMeter
      run: |
        JMETER_VERSION="5.5"
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
        tar -xvzf apache-jmeter-$JMETER_VERSION.tgz
        export PATH=$PATH:$GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/bin


    - name: Run JMeter test for CredentialsView
      run: |
        jmeter -n -t "CredentialsView Results Tree.jmx" -l results_credentials.jtl -e -o output_credentials
      env:
        CREDENTIALS_FILE: credential.csv
        LIST_FILE: list.csv
        POKEMON_NAME_FILE: pokemonName.csv

    - name: Run JMeter test for HTTP(S) Recorder
      run: |
        jmeter -n -t "testingHTTP(S) Test Script Recorder.jmx" -l results_http_recorder.jtl -e -o output_http_recorder
      env:
        CREDENTIALS_FILE: credential.csv
        LIST_FILE: list.csv
        POKEMON_NAME_FILE: pokemonName.csv

    - name: Upload JMeter results for CredentialsView
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results-credentialsview
        path: |
          results_credentials.jtl
          output_credentials

    - name: Upload JMeter results for HTTP(S) Recorder
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results-https-recorder
        path: |
          results_http_recorder.jtl
          output_http_recorder
